[package]
name = "iris-wallet"
version.workspace = true
edition.workspace = true

[dependencies]
iris-ztd = { workspace = true }
iris-crypto = { workspace = true }
iris-nockchain-types = { path = "../iris-nockchain-types" }
ibig = { workspace = true }
bs58 = "0.5.1"
